import argparse
import logging
import json
from collections import Counter
import os

# Set up basic logging
logging.basicConfig(level=logging.DEBUG, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')

# --- Layer Imports ---
# Layer 0 & 1: Ingestion and Hypothesis Generation
from discovery_stack.ingest import IngestionEngine
from discovery_stack.types import TargetConfig, PipelineStatus

# Layer 2: Probabilistic Inference
from discovery_stack.wrappers import BayesianWrapper

# Layer 3: Self-Consistency & Adversarial Validation
from validation.self_consistency.perturbation_tests import run_perturbation_test

# Layer 4: Physical & System Constraints (The Judge)
from discovery_stack.governance import DiscoveryGovernor

# Layer 5: Discovery Governance & Reporting
from governance.candidate_lifecycle import govern
from governance.decision_log import DecisionLog, log_rejection, log_promotion


# --- CONFIGURATION ---
import config as lite_config
MODEL_PATH = "models/keras_cacl_transformer_encoder.keras" 
# Create a results directory for the logs
os.makedirs(lite_config.RESULTS_DIR, exist_ok=True)
DECISION_LOG_PATH = os.path.join(lite_config.RESULTS_DIR, "discovery_decision_log.json")


def run_pipeline(tic_id: int, mission: str, sector: str):
    """
    Executes the full, governed discovery pipeline for a single target.
    """
    logger = logging.getLogger(__name__)
    logger.info(f"--- Starting GOVERNED Discovery Pipeline V2 for {mission} TIC {tic_id} ---")

    # 1. Initialize all pipeline components
    try:
        # Layer 0/1
        ingestion_engine = IngestionEngine()
        # Layer 2
        bayesian_wrapper = BayesianWrapper()
        # Layer 4
        governor = DiscoveryGovernor()
        # Layer 5
        decision_logger = DecisionLog(log_path=DECISION_LOG_PATH)
    except Exception as e:
        logger.critical(f"Failed to initialize pipeline components: {e}", exc_info=True)
        return

    # 2. Create Target Configuration
    target_config = TargetConfig(tic_id=tic_id, mission=mission, sector=sector)

    # 3. Stage 1: Ingestion
    hypotheses = ingestion_engine.scan_target(target_config)
    if not hypotheses:
        logger.info("Pipeline finished: No hypotheses generated by Ingestion Engine.")
        print("\n--- Final Summary ---")
        print("No signals were detected for this target.")
        return

    # 4. Process each hypothesis through the governance layers
    final_candidates = []
    rejection_reasons = Counter()

    for hypo in hypotheses:
        stability_score = 0.0 # Initialize stability_score
        # Layer 2: Probabilistic Inference
        hypo = bayesian_wrapper.predict(hypo)

        # Layer 4: Physical & System Constraints
        hypo = governor.audit(hypo)

        # Layer 3: Self-Consistency & Adversarial Validation
        if hypo.status != PipelineStatus.REJECTED:
            stability_score = run_perturbation_test(hypo, bayesian_wrapper)
            # This is where we would use the result of the test
            # For now, it's logged within the placeholder function.

        # Layer 5: Discovery Governance
        hypo = govern(hypo, audit_results={'stability_score': stability_score})
        
        # Layer 5: Reporting
        if hypo.status == PipelineStatus.ML_CANDIDATE:
            final_candidates.append(hypo)
            log_promotion(decision_logger, hypo)
        else:
            rejection_reason = hypo.logs[-1] if hypo.logs else "Unknown"
            rejection_reasons[rejection_reason] += 1
            log_rejection(decision_logger, hypo)


    # 5. Final Output
    logger.info("--- Pipeline Run Complete ---")
    print("\n--- Final Summary ---")
    print(f"Processed {len(hypotheses)} initial hypotheses.")
    
    if final_candidates:
        print(f"  >>> {len(final_candidates)} Valid Candidate(s) Promoted <<<")
        for candidate in final_candidates:
            print(json.dumps(candidate.__dict__, indent=2, default=str))
    else:
        print("  - No valid candidates met the final criteria for promotion.")

    if rejection_reasons:
        print("\n  - Summary of Rejected or Downgraded Hypotheses:")
        for reason, count in rejection_reasons.items():
            print(f"    - {reason}: {count}")
    
    print(f"\nFull decision log written to: {DECISION_LOG_PATH}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Run the Exoplanet Discovery Campaign Pipeline (V2 - Governed).")
    parser.add_argument("--tic_id", type=int, required=True, help="Tess Input Catalog (TIC) ID of the target star.")
    parser.add_argument("--mission", type=str, default="Kepler", help="Mission name (e.g., TESS, Kepler).")
    parser.add_argument("--sector", type=str, default="all", help="Observation sector for TESS.")
    
    args = parser.parse_args()

    run_pipeline(args.tic_id, args.mission, args.sector)
