import os
import logging
from datetime import datetime
import pandas as pd
import numpy as np
from pipeline.report_generator import create_spider_chart

logger = logging.getLogger(__name__)

def generate_candidate_dossier(hypothesis, output_dir):
    """
    Generates a structured HTML dossier for an exoplanet candidate.
    Includes light-curve diagnostics, transit parameters, and ML explanations.
    """
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    report_filename = f"dossier_{hypothesis.id}_{timestamp}.html"
    report_path = os.path.join(output_dir, report_filename)

    # Extract info from hypothesis
    params = hypothesis.signal_params
    cacl_explanation = hypothesis.metadata.get('cacl_explanation', {})
    
    # Generate Spider Chart if CACL data is available
    chart_filename = None
    if 'disagreement_matrix' in cacl_explanation:
        chart_filename = create_spider_chart(
            np.array(cacl_explanation['disagreement_matrix']), 
            hypothesis.id, 
            output_dir
        )

    html_content = f"""
    <!DOCTYPE html>
    <html lang='en'>
    <head>
        <meta charset='UTF-8'>
        <title>Candidate Dossier: {hypothesis.id}</title>
        <style>
            body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; max-width: 900px; margin: auto; padding: 20px; line-height: 1.6; color: #333; }}
            h1, h2 {{ color: #2c3e50; border-bottom: 2px solid #ecf0f1; padding-bottom: 10px; }}
            .summary-box {{ background: #f8f9fa; border-left: 5px solid #3498db; padding: 15px; margin: 20px 0; }}
            .grid {{ display: flex; flex-wrap: wrap; gap: 20px; }}
            .card {{ flex: 1; min-width: 250px; background: white; border: 1px solid #ddd; border-radius: 8px; padding: 15px; box-shadow: 0 2px 4px rgba(0,0,0,0.05); }}
            .metric-label {{ font-size: 0.9em; color: #7f8c8d; text-transform: uppercase; }}
            .metric-value {{ font-size: 1.4em; font-weight: bold; color: #2980b9; }}
            .cacl-section {{ background: #e8f4fd; padding: 20px; border-radius: 8px; margin-top: 20px; }}
            .veto-log {{ background: #fdf2f2; border-left: 5px solid #e74c3c; padding: 10px; font-family: monospace; }}
        </style>
    </head>
    <body>
        <h1>Exoplanet Candidate Dossier: {hypothesis.id}</h1>
        <p>Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>

        <div class="summary-box">
            <h2>Status: {hypothesis.status}</h2>
            <p><strong>Rationale:</strong> {hypothesis.rationale}</p>
        </div>

        <h2>Physical Parameters</h2>
        <div class="grid">
            <div class="card">
                <div class="metric-label">Orbital Period</div>
                <div class="metric-value">{params.get('orbital_period_days', 'N/A'):.4f} days</div>
            </div>
            <div class="card">
                <div class="metric-label">Transit Depth</div>
                <div class="metric-value">{params.get('depth', 0.0):.2%}</div>
            </div>
            <div class="card">
                <div class="metric-label">Estimated Radius</div>
                <div class="metric-value">{params.get('radius_earth', 'N/A'):.2f} R<sub>⊕</sub></div>
            </div>
        </div>

        <div class="cacl-section">
            <h2>ML Diagnostic (CACL)</h2>
            <div class="grid">
                <div style="flex: 1;">
                    <p><strong>Max Disagreement (&delta;):</strong> {cacl_explanation.get('max_disagreement', 'N/A'):.4f}</p>
                    <p><strong>Confidence Score:</strong> {cacl_explanation.get('confidence_score', 'N/A'):.4f}</p>
                    <p><strong>Context Flag:</strong> {cacl_explanation.get('context_flag', 'N/A')}</p>
                </div>
                <div style="flex: 1; text-align: center;">
                    {f'<img src="{chart_filename}" style="max-width: 100%;">' if chart_filename else '<p>No Spider Chart available.</p>'}
                </div>
            </div>
        </div>

        <h2>Audit & Validation Logs</h2>
        <div class="veto-log">
            {"<br>".join(hypothesis.logs) if hypothesis.logs else "No audit logs available."}
        </div>

        <footer style="margin-top: 50px; font-size: 0.8em; text-align: center; color: #95a5a6;">
            Generated by exo-discovery-stack v1.0.0
        </footer>
    </body>
    </html>
    """

    with open(report_path, 'w') as f:
        f.write(html_content)

    logger.info(f"Candidate dossier generated for {hypothesis.id}: {report_path}")
    return report_path
